"""empty message

Revision ID: c0697ca23187
Revises: cb3448b387aa
Create Date: 2020-01-25 22:57:37.512577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0697ca23187'
down_revision = 'cb3448b387aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('east', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('north', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('south', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('west', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_east'), 'user', ['east'], unique=False)
    op.create_index(op.f('ix_user_north'), 'user', ['north'], unique=False)
    op.create_index(op.f('ix_user_south'), 'user', ['south'], unique=False)
    op.create_index(op.f('ix_user_west'), 'user', ['west'], unique=False)
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True))
    op.drop_index(op.f('ix_user_west'), table_name='user')
    op.drop_index(op.f('ix_user_south'), table_name='user')
    op.drop_index(op.f('ix_user_north'), table_name='user')
    op.drop_index(op.f('ix_user_east'), table_name='user')
    op.drop_column('user', 'west')
    op.drop_column('user', 'south')
    op.drop_column('user', 'north')
    op.drop_column('user', 'east')
    # ### end Alembic commands ###
